### ISSUE TITLE
[GCS] Access to directory DIODE_data

### ISSUE THREAD

**Issue by CVStack** [NVlabs/DIODE#11]
Hi.

I want to access the DIODE dataset.

Please give the access to it,

My gmail is _

Thank you,

**Comment by akshaychawla** [comment]
Hi @CVStack , I've re-enabled the permissions on the GCS bucket for 1 week.
Can you confirm that you can view and download it from https://console.cloud.google.com/storage/browser/diode-yolo-wacv ? 
The download permissions will be again disabled on January 2nd, 2022.

**Comment by CVStack** [comment]
I checked them and downloaded well.

Thank you!

**Comment by akshaychawla** [comment]
Thanks for the prompt response @CVStack. The permissions have been turned off now.
