### ISSUE TITLE
[GCS]need access to data

### ISSUE THREAD

**Issue by touristourist** [NVlabs/DIODE#12]
Hi @akshaychawla , thank you for the code, can you grant me access to the GCS data?

**Comment by akshaychawla** [comment]
Thanks for your interest in our work @touristourist. I have enabled the download permissions for the GCS bucket for 1 week i.e upto January 4, 2022. Please confirm that you can view and download the data.
Link: https://console.cloud.google.com/storage/browser/diode-yolo-wacv

**Comment by touristourist** [comment]
OK, thank you very much!

**Comment by akshaychawla** [comment]
@touristourist I have disabled the download permissions today (January 5, 2022). Please re-open this issue if you were unable to download data from the bucket.
