### ISSUE TITLE
Try on two stage detector

### ISSUE THREAD

**Issue by merlinarer** [NVlabs/DIODE#9]
Hello, have you try on two stage detector, faster rcnn for example ?

**Comment by akshaychawla** [comment]
Hi @merlinarer , welcome back. 

We did not look into two stage detectors such as Faster RCNN. However, it shouldn't be too hard to adapt to faster RCNN. 

For generating images, you will have to modify this script https://github.com/NVlabs/DIODE/blob/yolo/deepinversion_yolo.py. The model will have to be changed to a Faster-RCNN and the `task_loss` will change to the detection loss for a faster-rcnn model. All other losses such as image prior losses and deep feature loss will remain the same. 

For distillation, here is a paper that performs knowledge distillation for Faster RCNN models: https://arxiv.org/abs/1906.03609
